# Activate DSEFS
- name: Activate and configure DSEFS on node
  yedit:
    src: "{{ dse_config_dir }}/dse.yaml"
    edits:
    - key: dsefs_options.enabled
      value: true
    - key: dsefs_options.data_directories.dir
      value: "{{dsefs_data_file_directory}}"
