---
#EXPECTS: [hosts: dse] or [hosts: opsc_dsecore],  [become: yes] [become_method: sudo] on playbook call

- name: Copy individual keystore to each [hosts dse] or [hosts opsc_dsecore] node
  copy:
    src: "{{ssl_certs_path}}/{{inventory_hostname}}-keystore.jks"
#    src: "{{ssl_certs_path}}/{{inventory_hostname}}-pkcs12-keystore.jks"
    dest: "{{cluster_keystore_path}}"
    owner: "{{cassandra_owner}}"
    group: "{{cassandra_group}}"
    mode: 0644
