
- name: Configure seeds in exiting nodes to include new datacenter seeds  (cassandra.yaml)
  lineinfile:
    name: "{{ dse_config_dir }}/cassandra/cassandra.yaml"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    owner: cassandra
    group: cassandra
    mode: 0644
  with_items:
    - { regexp: '- seeds\:',         line: "          - seeds: {{ seeds }}" }
