---
# WARNING: This role should only be run once per cluster on a single DSE node

# Change system_auth and dse_security RF to 3-5 for each DC and change to NetworkToplogyStrategy from SimpleStrategy.
# https://docs.datastax.com/en/dse/5.1/dse-admin/datastax_enterprise/security/secAuthAndRbacAbout.html
# https://docs.datastax.com/en/dse/5.1/dse-admin/datastax_enterprise/security/Auth/secEnableDseAuthenticator.html

#- name: Create dse_security ALTER KEYSPACE string
#  set_fact:
#    _dse_security_alter_keyspace: ""
#- debug:
#    msg: "{{ _dse_security_alter_keyspace }}"

- name: ALTER the replication_factor and replication class for dse_security KEYSPACE
  command: cqlsh -u {{secure_super_user_account}} -p {{secure_super_user_password}}
  with_items:
    - "ALTER KEYSPACE dse_security WITH REPLICATION = {'class': 'NetworkToplogyStrategy', 'replication_factor': {{security_table_replication_factor}} };"
    - EXIT;
    
- name: ALTER the replication_factor and replication class for system_auth KEYSPACE
  command: cqlsh -u {{secure_super_user_account}} -p {{secure_super_user_password}}
  with_items:
    - "ALTER KEYSPACE system_auth WITH REPLICATION = {'class': 'NetworkToplogyStrategy', 'replication_factor': {{security_table_replication_factor}} };"
    - EXIT;
