
- name: Configure /etc/hosts
  lineinfile:
    name: "/etc/hosts"
    regexp: '^127\.0\.0\.1'
    line: "{{'127.0.0.1   localhost localhost.localdomain ' + hostname }}"
  vars:
    hostname: "{{ hostvars[inventory_hostname].private_dns if is_self_signed_root_cert | bool else ansible_hostname + '.' + ssl_certs_common_name}}"
#    owner: cassandra
#    group: cassandra
#    mode: 0644
