---

# This role configures the [/etc/opscenter/opscenterd.conf] file

# Configure opsc webserver security
# https://docs.datastax.com/en/opscenter/6.5/opsc/configure/opscConfiguringEnablingHttps_t.html

# Configure opsc -> agent security
# https://docs.datastax.com/en/opscenter/6.5/opsc/configure/opscEnableSSLpkg.html

- set_fact: opscenterd_conf_template="opscenterd_conf_{{dse_major_version}}.j2"

- template:
    src: "templates/{{opscenterd_conf_template}}"
    dest: /etc/opscenter/opscenterd.conf
    owner: "{{opscenter_owner}}"
    group: "{{opscenter_group}}"
    mode: 0644




