---
- name: Install python pip
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - "python3-pip"
    - "python3-dev"
    - "build-essential"
    
#- name: Install pyOpenSSL via pip
#  pip:
#    name: pyOpenSSL
#    state: present

- name: Install ruamel.yaml via pip ( used by ansible/library/yedit)
  pip:
    name: ruamel.yaml
    state: present

#Install the crypto extensions
- name: Install Java JCE - Java Cryptography Extensions
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - "oracle-java8-unlimited-jce-policy"
    
    
