---
- name: Install python pip
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - "python-pip"
    - "python-dev"
    - "build-essential"
    
- name: Install pyOpenSSL via pip
  pip:
    name: pyOpenSSL
    state: present

- name: Install ruamel.yaml via pip ( used by ansible/library/yedit)
  pip:
    name: ruamel.yaml
    state: present

#The repo should aready be configured when Java was installed but lets keep it idempotent
- name: Add apt repository
  apt_repository:
      repo: 'ppa:webupd8team/java'
      state: present
      update_cache: yes

- name: Accept license
  debconf:
    name: 'oracle-java8-installer'
    question: 'shared/accepted-oracle-license-v1-1'
    value: 'true'
    vtype: 'select'

- name: Install java
  apt: name={{ item }} state=present
  with_items:
      - oracle-java8-installer
      - ca-certificates
      - oracle-java8-set-default

- name: Install Java JCE - Java Cryptography Extensions
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - "oracle-java8-unlimited-jce-policy"
    
    
