---
#WARNING: this task runs on the ansible host only: localhost 
- name: Import SSL certificate to a local truststore, create truststore if it doesn't exist
  java_cert:
    cert_alias: "{{ansible_fqdn}}"
    cert_path: "/etc/ssl/{{ansible_fqdn}}/{{ansible_fqdn}}.pem"
    keystore_path: /tmp/.truststore
    keystore_pass: "{{ cluster_truststore_password }}"
    keystore_create: yes
    state: present

    
    
    

