---

#NOT CURRENTLY USED

#EXPECTS: [hosts: localhost] [become: no] [connection: local] in playbook call
- name: Create an OPSC truststore on the ansible machine and import each node's public certificate.
  command: keytool -import -v -trustcacerts -noprompt -alias "{{item}}" -file "{{ssl_certs_path}}/{{item}}.crt_signed" -keystore "{{ssl_certs_path}}/opscenter_truststore.jks" -storepass "{{cluster_truststore_password}}" -keypass "{{cluster_truststore_password}}"
  with_items: "{{ groups['dse'] }}"

