---

# This role configures the [/etc/opscenter/clusters/cluster_name.conf] file

#configure seperate opscenter storage cluster
#configure agent -> dse encrytption
#configure opscenter -> dse encryption

- name: populate cluster_name.conf
  template:
    src: cluster_name.j2
    dest: "/etc/opscenter/clusters/{{hostvars[groups['dse'][0]]['cluster_name']}}.conf"
    
    
