---
#EXPECTS: [hosts: localhost] [become: no] [connection: local] in playbook call

#empty the directory
- name: Empty "{{ssl_certs_path}}" directory
  shell: cd "{{ssl_certs_path}}" && find -mindepth 1 -maxdepth 1 -print0 | xargs -0 rm -rf --

#raw cmd line call: 
#>cd /etc/ssl/SelfSignRootCA
#>openssl req -new -x509 -nodes -subj /CN=SelfSignRootCA/OU=cluster_name/O=DataStax/C=US/ -keyout SelfSignRootCA.key -out SelfSignRootCA.pem -days 365
- name: Generate self-signed SSL certificate
  command: >
    openssl req -new -x509 -nodes 
    -subj "/CN={{ '*.' if is_wildcard_cert | bool else '' }}{{ssl_certs_common_name}}/OU={{ssl_cluster_name}}/O={{ssl_certs_organization}}/C={{ssl_certs_country}}" 
    -keyout "{{ssl_certs_common_name}}".key -out "{{ssl_certs_common_name}}".pem 
    -days "{{ssl_certs_days}}"
  args:
    chdir: "{{ssl_certs_path}}"

