---
- name: Gracefully shutdown cassandra node
  command: "{{ item }}"
  with_items:
    - "nodetool -u {{secure_super_user_account}} -pw {{secure_super_user_password}} flush"
#    - "nodetool snapshot"
#    - "nodetool disablethrift"
    - "nodetool -u {{secure_super_user_account}} -pw {{secure_super_user_password}} disablebinary"
    - "nodetool -u {{secure_super_user_account}} -pw {{secure_super_user_password}} disablegossip"
    - "nodetool -u {{secure_super_user_account}} -pw {{secure_super_user_password}} drain"

- name: Shut down "cassandra/dse" service
  service:
    name: "{{ srvc_name }}"
    state: stopped
    
- name: Wait for Cassandra process to completely stop
  wait_for:
    host: "{{ ansible_host }}"
    port: 9042
    state: drained
    delay: 1
    timeout: 300
