
# Stop datastax agent on new datacenter nodes
- hosts: add_datacenter
  any_errors_fatal: true
  become: true
  become_method: sudo
  tasks:    
    - name: Stop datastax-agent service
      service:
        name: "datastax-agent"
        state: stopped
