---
# Get the current timestamp and register datastax debian packages
- hosts: add_node[0]
  any_errors_fatal: true
  become: true
  become_method: sudo
  tasks:
  - name: Get the current timestamp
    shell: 'date +%Y%m%d%H%M%S'
    register: current_timestamp
  roles:
  - { role: datastax_pkg }

# populate the seeds list by iterating over DSE nodes in the hosts file
- hosts: dse
  any_errors_fatal: true
  become: true
  become_method: sudo
  roles:
    - { role: dse_common }

# Install and configure DSE
- hosts: add_node[0]
  any_errors_fatal: true
  become: true
  become_method: sudo
  roles:
    - { role: datastax_pkg }
    - { role: java8_inst }
    - { role: dse_osparam_change }
    - { role: dse_instbin }
    - { role: dse_updcfg }
    
# Install and configure datastax-agent
- hosts: add_node[0]
  any_errors_fatal: true
  become: true
  become_method: sudo
  tasks:
  
    - name: Install datastax-agent on DSE nodes
      apt:
        name: "datastax-agent={{opsc_ver_target}}"
        state: present
        update_cache: yes
