
# Activate DSE Unified Authentication for JMX on new node -> cassandra-env.sh
- hosts: add_datacenter
  any_errors_fatal: true
  become: true
  become_method: sudo
  roles:
    - { role: security_jmx_auth_activate }
