
- hosts: add_node[0]
  any_errors_fatal: true
  become: true
  become_method: sudo
  vars:
    is_analytic: "{{ lookup('ini', 'SPARK_ENABLED type=properties file=/tmp/dse') }}"
  roles:
    - { role: security_spark_configure, when: is_analytic | bool }
    
- hosts: add_node[0]
  any_errors_fatal: true
  become: true
  become_method: sudo
  vars:
    is_analytic: "{{ lookup('ini', 'SPARK_ENABLED type=properties file=/tmp/dse') }}"
  roles:
    - { role: security_spark_alwaysonsql_configure, when: is_analytic | bool and activate_alwaysonsql | bool and activate_alwaysonsql_ssl | bool  and dse_major_version >= 6.0}
