
# Change security table replication and strategy, replace insecure SuperUser all via CQLSH on a single DSE cluster node
- hosts: dse[0]
  any_errors_fatal: true
  become: true
  become_method: sudo
  roles:
    - { role: security_prerequisites }


# Install DSE security software dependencies on all nodes
- hosts: dse
  any_errors_fatal: true
  become: true
  become_method: sudo
  roles:
    - { role: security_install }
    
#generate self signed certificates OR CA certificates, keystores and truststores all on localhost
- hosts: localhost
  any_errors_fatal: true
  become: true
  become_method: sudo
  roles:
    - { role: security_create_selfsign_cert } #optional if CA certs supplied
    - { role: security_create_truststores }
    - { role: security_create_keystores }


#distribute keystores and truststores to all dse nodes
- hosts: dse
  any_errors_fatal: true
  become: true
  become_method: sudo
  roles:
    - { role: security_distribute_truststores }
    - { role: security_distribute_keystores }
    
    
# Install DSE security features on all nodes <---- EDIT LIST
- hosts: dse
  any_errors_fatal: true
  become: true
  become_method: sudo
  roles:
    - { role: security_node_to_node }
    - { role: security_client_to_node }
    - { role: security_dse_unified_auth_activate }


#Stop and restart all nodes in seed order
# Stop DSE seed nodes 
- hosts: dse
  any_errors_fatal: true
  name: Start seed node 
  serial: 1
  become: true
  become_method: sudo
  vars:
    srvc_name: dse
  roles:
    - { role: stop_srvc, when: seed == 'true' } 

# Stop DSE non-seed nodes 
- hosts: dse
  any_errors_fatal: true
  name: Start non-seed node one by one
  serial: 1
  become: true
  become_method: sudo
  vars:
    srvc_name: dse
  roles:
    - { role: stop_srvc, when: seed == 'false' }

# Start DSE seed nodes 
- hosts: dse
  any_errors_fatal: true
  name: Start seed node 
  serial: 1
  become: true
  become_method: sudo
  vars:
    srvc_name: dse
  roles:
    - { role: start_srvc, when: seed == 'true' } 

# Start DSE non-seed nodes 
- hosts: dse
  any_errors_fatal: true
  name: Start non-seed node one by one
  serial: 1
  become: true
  become_method: sudo
  vars:
    srvc_name: dse
  roles:
    - { role: start_srvc, when: seed == 'false' }

