
# create certificate directory
- hosts: localhost
  any_errors_fatal: true
  become: no
  connection: local
  roles:
    - { role: security_create_root_certificate_directory } 


#generate self signed certificates - OPTIONAL IF CA ROOT CERT SUPPLIED.
- hosts: localhost
  any_errors_fatal: true
  become: no
  connection: local
  roles:
    - { role: security_create_root_certificate } 

    
#create core DSE / OPSC storage node truststores and keystores (local)
- hosts: localhost
  any_errors_fatal: true
  become: no
  connection: local
  roles:
    - { role: security_create_truststores }
    - { role: security_create_keystores }


# Distribute combined OPSC DSECore / DSE truststores and keystores to DSE nodes 
# - (OPSC DSECore K/T Stores deployed but not currently used)
# These roles work in tandem with opsc_security.yml - this call only does the DSE cluster distribution
- hosts: dse
  any_errors_fatal: true
  become: yes
  become_method: sudo
  roles:
    - { role: security_distribute_truststores }
    - { role: security_distribute_keystores }

    
# Install DSE security features on all nodes
- hosts: dse
  any_errors_fatal: true
  become: true
  become_method: sudo
  roles:
    - { role: security_node_to_node }
    - { role: security_client_to_node }
    



