---
# Get the current timestamp and register datastax debian packages
- hosts: dse
  any_errors_fatal: true
  become: true
  become_method: sudo
  tasks:
  - name: Get the current timestamp
    shell: 'date +%Y%m%d%H%M%S'
    register: current_timestamp
  roles:
  - { role: datastax_pkg }


# Install and configure DSE
- hosts: dse
  any_errors_fatal: true
  become: true
  become_method: sudo
  roles:
    - { role: java8_inst }
    - { role: dse_osparam_change }
    - { role: dse_common }
    - { role: dse_instbin }
    - { role: dse_updcfg }
