
# Install DSE security software dependencies on all nodes
- hosts: dse
  any_errors_fatal: true
  become: yes
  become_method: sudo
  roles:
#    - { role: security_install }

#generate self signed certificates - OPTIONAL IF CA ROOT CERT SUPPLIED.
- hosts: localhost
  any_errors_fatal: true
  become: no
  connection: local
  roles:
    - { role: security_dse_create_root_certificate } 

    
#create truststores and keystores (local)
- hosts: localhost
  any_errors_fatal: true
  become: no
  connection: local
  roles:
    - { role: security_dse_create_truststores }
    - { role: security_dse_create_keystores }


#distribute truststores and keystores (local/remote)
- hosts: dse
  any_errors_fatal: true
  become: yes
  become_method: sudo
  roles:
    - { role: security_dse_distribute_truststores }
    - { role: security_dse_distribute_keystores }

    
# Install DSE security features on all nodes <---- EDIT LIST
- hosts: dse
  any_errors_fatal: true
  become: true
  become_method: sudo
  roles:
    - { role: security_dse_node_to_node }
    - { role: security_dse_client_to_node }
    



