

- hosts: localhost
  any_errors_fatal: true
  become: no
  connection: local
  roles:
    - { role: security_change_superuser}
  vars:
    cql_target: "{{ groups['opsc_dsecore'][0] }}"
    is_cql_target_ssl: false
