
# Stop opsc_srv
- hosts: opsc_srv
  any_errors_fatal: true
  become: true
  become_method: sudo
  tasks: 
  - name: Stop OpsCenter service
    service:
      name: "opscenterd"
      state: stopped
          
# Stop all DSE agents
- hosts: datastax_agent 
  any_errors_fatal: true
  become: true
  become_method: sudo
  tasks:
  - name: Stop datastax-agent service
    service:
      name: "datastax-agent"
      state: stopped

# Install DSE security software dependencies on all OPSC DSECore nodes
- hosts: opsc_dsecore
  any_errors_fatal: true
  become: true
  become_method: sudo
  roles:
    - { role: security_install }
       
# Configure OPSC SERVER [opscenterd.conf]: webserver HTTPS security, OPSC->Agent security
- hosts: opsc_srv
  any_errors_fatal: true
  become: true
  become_method: sudo
  roles:
    - { role: security_opsc_config }
    
# Distribute combined OPSC DSECore / DSE truststores and keystores to OPSC nodes 
# - (OPSC DSECore K/T Stores deployed but not currently used)
- hosts: opsc_dsecore
  any_errors_fatal: true
  become: yes
  become_method: sudo
  roles:
    - { role: security_distribute_truststores }
    - { role: security_distribute_keystores }
    
# TODO: Configure all DSE agents with Transport security - need AWS environment
- hosts: opsc_srv
  any_errors_fatal: true
  become: true
  become_method: sudo
  roles:
    - { role: security_opsc_agents_configure }

# Start OPSC SERVER
- hosts: opsc_srv
  any_errors_fatal: true
  become: true
  become_method: sudo
  tasks: 
  - name: Start OpsCenter service
    service:
      name: "opscenterd"
      state: started
      
# Start all DSE agents
- hosts: datastax_agent 
  any_errors_fatal: true
  become: true
  become_method: sudo
  tasks:
  - name: Start datastax-agent service
    service:
      name: "datastax-agent"
      state: started


      
