
# Install DSE security software dependencies on all opscenter storage nodes
- hosts: opsc_dsecore
  any_errors_fatal: true
  become: true
  become_method: sudo
  roles:
    - { role: security_install }
    
# Configure opscenter agents -> currently a noop, should auto pull config from opsc_server
- hosts: dse
  any_errors_fatal: true
  become: true
  become_method: sudo
  roles:
    - { role: security_opscenter_agents }

# Install and configure OpsCenter server->cluster security and webserver HTTPS security
- hosts: opsc_srv
  any_errors_fatal: true
  become: true
  become_method: sudo
  roles:
    - { role: security_opscenter }
    
 #TODO - need to restart opsc_srv then restart all agents
    

