
  
# Configure OPSC SERVER [opscenterd.conf]: 
# webserver HTTPS security, 
# OPSC authentication activate
# OPSC -> Agent security
- hosts: opsc_srv
  any_errors_fatal: true
  become: true
  become_method: sudo
  roles:
    - { role: security_opsc_configure }
    
# Distribute combined OPSC DSECore / DSE truststores and keystores to OPSC nodes 
# - (OPSC DSECore K/T Stores deployed but not currently used)
# These roles work in tandem with dse_security.yml - this call only does the OPSC DSECore cluster distribution
- hosts: opsc_dsecore
  any_errors_fatal: true
  become: yes
  become_method: sudo
  roles:
    - { role: security_distribute_truststores }
    - { role: security_distribute_keystores }
    
# Fetch the pre-built (at install time) /var/lib/opscenter/ssl/agentKeyStore from the OPSC SERVER
- hosts: opsc_srv
  any_errors_fatal: true
  become: true
  become_method: sudo
  roles:
    - { role: security_opsc_agent_fetch_keystore }
    
# Distribute the pre-built (at install time) /var/lib/opscenter/ssl/agentKeyStore to DSE nodes
- hosts: dse
  any_errors_fatal: true
  become: true
  become_method: sudo
  roles:
    - { role: security_opsc_agent_distribute_keystore }

# Activate OPSC SERVER -> Agent SSL in Agent address.yaml
- hosts: dse
  any_errors_fatal: true
  become: true
  become_method: sudo
  roles:
    - { role: security_opsc_agents_activate_ssl }

# Start OPSC SERVER
- hosts: opsc_srv
  any_errors_fatal: true
  become: true
  become_method: sudo
  tasks: 
  - name: Start OpsCenter service
    service:
      name: "opscenterd"
      state: started
      
# Start all DSE agents
- hosts: datastax_agent 
  any_errors_fatal: true
  become: true
  become_method: sudo
  tasks:
  - name: Start datastax-agent service
    service:
      name: "datastax-agent"
      state: started


      
