
# Conditionally Activate DSEFS on Spark nodes
# 
- hosts: dse_analytics
  any_errors_fatal: true
  become: true
  become_method: sudo
  roles:
    - { role: spark_dsefs_configure, when: activate_dsefs | bool }
  
# Conditionally Activate AlwaysOnSQL on Spark nodes
#     
- hosts: dse_analytics
  any_errors_fatal: true
  become: true
  become_method: sudo
  roles:
    - { role: spark_alwaysonsql_configure, when: activate_alwaysonsql | bool and dse_major_version >= 6.0 } 
    
# Configure cleanup directory
- hosts: dse_analytics
  any_errors_fatal: true
  become: true
  become_method: sudo
  roles:
    - { role: spark_worker_directory_cleanup_configure }


# Configure log rolling   
- hosts: dse_analytics
  any_errors_fatal: true
  become: true
  become_method: sudo
  roles:
    - { role: spark_worker_log_rolling_configure }
