

# Fetch the pre-built (at install time) agentKeyStore from the OPSC SERVER
- hosts: dse
  any_errors_fatal: true
  become: true
  become_method: sudo
  roles:
    - { role: security_opsc_agent_distribute_keystore }
