# Install and configure datastax-agent
- hosts: datastax_agent 
  any_errors_fatal: true
  become: true
  become_method: sudo
  tasks:
    - name: Configure stomp_address
      lineinfile:
        name: "/var/lib/datastax-agent/conf/address.yaml"
        regexp: "{{ item.regexp }}"
        line: "{{ item.line }}"
      with_items:
        - { regexp: 'stomp_interface', line: "stomp_interface: {{ groups['opsc_srv'][0] }}" }
        - { regexp: '# use_ssl: 0', line: "use_ssl: true" }
        
    - name: Start datastax-agent service
      service:
        name: "datastax-agent"
        state: started
