

# Start all DSE agents
- hosts: datastax_agent 
  any_errors_fatal: true
  become: true
  become_method: sudo
  tasks:
  - name: Start datastax-agent service
    service:
      name: "datastax-agent"
      state: started
