

- hosts: localhost
  any_errors_fatal: true
  become: no
  connection: local
  tasks:
    - name: DROP default insecure cassandra/cassandra superuser account
      cassandra_role:
        state: absent
        name: "{{default_super_user_account}}"
        is_ssl: false
        cert_path: test.crt_signed"
        login_hosts: "{{ groups['dse'][0] }}"
        login_user: "{{secure_super_user_account}}"
        login_password: "{{secure_super_user_password}}"
