

- hosts: dse 
  any_errors_fatal: true
  become: true
  become_method: sudo
  tasks:
  - name: Install ruamel.yaml via pip ( used by ansible/library/yedit)
    pip:
     name: ruamel.yaml
     state: present
