# Configure OpsCenter [cluster_name.conf]: storage_cassandra, monitoring_cassandra, security etc
- hosts: opsc_srv
  any_errors_fatal: true
  become: true
  become_method: sudo
  roles:
    - { role: security_opsc_cluster_configure }
