---


- name: Do non wildcard certs
  include: tasks/non_wildcard_certs.yml
  when: not is_wildcard_cert | bool

- name: Do wildcard certs
  include: tasks/wildcard_certs.yml
  when: is_wildcard_cert | bool